[tool.poetry]
name = "balchem"
version = "0.1.0"
description = "Balances chemical equations"
authors = ["Leo Paukkonen"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
